// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: address.sql

package sqlc

import (
	"context"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO apollo.address (street, number, extra_line, postal_code, city, country)
	VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
	id, street, number, postal_code, city, country, extra_line
`

type CreateAddressParams struct {
	Street     string
	Number     int32
	ExtraLine  *string
	PostalCode int32
	City       string
	Country    string
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (ApolloAddress, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.Street,
		arg.Number,
		arg.ExtraLine,
		arg.PostalCode,
		arg.City,
		arg.Country,
	)
	var i ApolloAddress
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.Number,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.ExtraLine,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM apollo.address
WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddress = `-- name: GetAddress :one
SELECT
	id, street, number, postal_code, city, country, extra_line
FROM
	apollo.address
WHERE
	id = $1
LIMIT 1
`

func (q *Queries) GetAddress(ctx context.Context, id int32) (ApolloAddress, error) {
	row := q.db.QueryRow(ctx, getAddress, id)
	var i ApolloAddress
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.Number,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.ExtraLine,
	)
	return i, err
}

const listAddresses = `-- name: ListAddresses :many
SELECT
	id, street, number, postal_code, city, country, extra_line
FROM
	apollo.address
`

func (q *Queries) ListAddresses(ctx context.Context) ([]ApolloAddress, error) {
	rows, err := q.db.Query(ctx, listAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApolloAddress
	for rows.Next() {
		var i ApolloAddress
		if err := rows.Scan(
			&i.ID,
			&i.Street,
			&i.Number,
			&i.PostalCode,
			&i.City,
			&i.Country,
			&i.ExtraLine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE
	apollo.address
SET
	street = COALESCE($2, street),
	number = COALESCE($3, number),
	extra_line = COALESCE($4, extra_line),
	postal_code = COALESCE($5, postal_code),
	city = COALESCE($6, city),
	country = COALESCE($7, country)
WHERE
	id = $1
RETURNING
	id, street, number, postal_code, city, country, extra_line
`

type UpdateAddressParams struct {
	ID         int32
	Street     *string
	Number     *int32
	ExtraLine  *string
	PostalCode *int32
	City       *string
	Country    *string
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (ApolloAddress, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Street,
		arg.Number,
		arg.ExtraLine,
		arg.PostalCode,
		arg.City,
		arg.Country,
	)
	var i ApolloAddress
	err := row.Scan(
		&i.ID,
		&i.Street,
		&i.Number,
		&i.PostalCode,
		&i.City,
		&i.Country,
		&i.ExtraLine,
	)
	return i, err
}
