// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApolloAccount struct {
	UserID     int32
	Provider   string
	ProviderID string
}

type ApolloAccountCache struct {
	ID         pgtype.UUID
	Name       *string
	Email      *string
	Provider   string
	ProviderID string
	Created    pgtype.Timestamptz
}

type ApolloAddress struct {
	ID         int32
	Street     string
	Number     int32
	PostalCode int32
	City       string
	Country    string
	ExtraLine  *string
}

type ApolloOrganisation struct {
	ID       int32
	Name     string
	ParentID *int32
}

type ApolloOrganisationUser struct {
	ID             int32
	UserID         int32
	OrganisationID int32
}

type ApolloOrganisationUsersPermissiongroup struct {
	OrganisationUsersID int32
	PermissionGroupID   int32
}

type ApolloPermission struct {
	Name string
}

type ApolloPermissiongroup struct {
	ID   int32
	Name *string
}

type ApolloPermissiongroupPermission struct {
	GroupID    int32
	Permission string
	Enabled    bool
}

type ApolloUser struct {
	ID     int32
	Name   string
	Email  string
	Joined pgtype.Timestamptz
	Admin  bool
}

type ApolloUserPermissiongroupMembership struct {
	GroupID int32
	UserID  int32
}
