// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApolloAccount struct {
	UserID     int32
	Provider   string
	ProviderID string
}

type ApolloAccountCache struct {
	ID         pgtype.UUID
	Name       *string
	Email      *string
	Provider   string
	ProviderID string
	Created    pgtype.Timestamptz
}

type ApolloUser struct {
	ID     int32
	Name   string
	Email  string
	Joined pgtype.Timestamptz
}
