name: Code integration checks

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      main

permissions:
  contents: read
  checks: write # Add checks to PR

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Setup templ
      run: go install github.com/a-h/templ/cmd/templ@latest
    - name: Setup Just
      uses: extractions/setup-just@v2
    - name: Compile generated files
      run: just generate
    - name: Archive generated output
      uses: actions/upload-artifact@v4
      with:
        name: generated
        path: |
          server
          migrations

  build:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Setup Just
      uses: extractions/setup-just@v2
    - name: Download generated files
      uses: actions/download-artifact@v4
      with:
        name: generated
    - name: Build
      run: just build

  test:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Setup Just
      uses: extractions/setup-just@v2
    - name: Download generated files
      uses: actions/download-artifact@v4
      with:
        name: generated
    - name: Create build
      run: just build
    - name: Test
      run: just test

  lint:
    runs-on: ubuntu-latest
    needs: generate
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: Download generated files
      uses: actions/download-artifact@v4
      with:
        name: generated
    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --timeout 3m
